{
 "title": "Backend",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "branch", "label": "Branch", "query": "main" },
   {
    "name": "attendee_count_export_service",
    "query": "$branch-attendee-count-exporter"
   },
   { "name": "anycable_go_service", "query": "$branch-anycable-go" },
   { "name": "web_service", "query": "$branch-web" },
   { "name": "worker_service", "query": "$branch-worker" },
   { "name": "hpa_web", "query": "keda-hpa-$branch-web" },
   { "name": "hpa_worker", "query": "keda-hpa-$branch-worker" },
   { "name": "hpa_ws", "query": "keda-hpa-$branch-ws" },
   { "name": "hpa_rpc", "query": "keda-hpa-$branch-rpc" },
   { "name": "rpc_service", "query": "$branch-rpc" }
  ]
 },
 "panels": [
  {
   "title": "Total requests in the selected period",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{ingress=~\"$branch\"}[${__range_s}s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active vs Total Attendees",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(anycable_go_clients_uniq_num{service=\"$anycable_go_service\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(attendee_count{service=~\"$attendee_count_export_service\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(kube_horizontalpodautoscaler_status_current_replicas{horizontalpodautoscaler=~\"$hpa_web\"})",
     "legendFormat": "Web"
    },
    {
     "expr": "avg(kube_horizontalpodautoscaler_status_current_replicas{horizontalpodautoscaler=\"$hpa_worker\"})",
     "legendFormat": "Worker"
    },
    {
     "expr": "avg(kube_horizontalpodautoscaler_status_current_replicas{horizontalpodautoscaler=\"$hpa_ws\"})",
     "legendFormat": "AnyCable"
    },
    {
     "expr": "avg(kube_horizontalpodautoscaler_status_current_replicas{horizontalpodautoscaler=\"$hpa_rpc\"})",
     "legendFormat": "RPC"
    }
   ]
  },
  {
   "title": "Request queue time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(ruby_queue_time_bucket{service=\"$web_service\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(ruby_queue_time_bucket{service=\"$web_service\"}[5m])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(ruby_queue_time_bucket{service=\"$web_service\"}[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Successful requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(ruby_http_requests_total{service=\"$web_service\",status=~\"^[23].*\"}[1m])) by (status) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(ruby_http_requests_total{service=\"$web_service\",status=~\"^[45].*\"}[1m])) by (status) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Avg Response Time (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(ruby_http_request_duration_seconds{service=\"$web_service\"})",
     "legendFormat": "Avg Response Time"
    }
   ]
  },
  {
   "title": "Tot. Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate(ruby_http_requests_total{service=\"$web_service\"}[1m]))",
     "legendFormat": "Req/sec"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Avg Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(sum by(pod) (ruby_rss{service=\"$web_service\"}))",
     "legendFormat": "Web"
    },
    {
     "expr": "avg(sum by(pod) (ruby_rss{service=\"$worker_service\"}))",
     "legendFormat": "Worker"
    }
   ]
  },
  {
   "title": "Avg Objects allocation rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "avg by(container) (rate(ruby_allocated_objects_total{service=\"$web_service\"}[5m]))",
     "legendFormat": "Avg Allocati ons"
    }
   ]
  },
  {
   "title": "SQL duration seconds by controller/action",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "avg by(controller, action) (ruby_http_request_sql_duration_seconds{service=\"main-web\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request duration by controller/action",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "avg(ruby_http_request_duration_seconds) by(controller, action)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ActiveRecord Connections - Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "sum(ruby_active_record_connection_pool_connections)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ActiveRecord Connections - Waiting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "sum(ruby_active_record_connection_pool_waiting{service=\"main-web\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ActiveRecord Connections - Busy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "sum(ruby_active_record_connection_pool_busy)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Record Connections - Idle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "sum(ruby_active_record_connection_pool_idle)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}