{
 "title": "Backend - Rails Metrics",
 "description": "A generic dashboard for metrics collected by the prometheus_exporter gem",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(ruby_rss,kubernetes_namespace)"
   },
   {
    "name": "controller",
    "query": "label_values(ruby_http_requests_total{kubernetes_namespace=\"$namespace\"},controller)"
   },
   {
    "name": "action",
    "query": "label_values(ruby_http_requests_total{kubernetes_namespace=\"$namespace\",controller=~\"$controller\"},action)"
   },
   {
    "name": "job",
    "query": "label_values(ruby_sidekiq_jobs_total{kubernetes_namespace=\"$namespace\"},job_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Web Workers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ruby_rss{type=~'master|web|puma_master|puma_worker',kubernetes_namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Sidekiq Workers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ruby_rss{type='sidekiq',kubernetes_namespace='$namespace'})"
    }
   ]
  },
  {
   "title": "Requests / h",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ruby_http_requests_total{kubernetes_namespace=\"$namespace\",controller!=\"status\",controller=~\"$controller\",action=~\"$action\"}[60m]) * 60 * 60)"
    }
   ]
  },
  {
   "title": "Sidekiq Jobs / h",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ruby_sidekiq_job_duration_seconds_count{kubernetes_namespace=\"$namespace\"}[60m]) * 60 * 60)"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request Duration (all actions)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile(0.95, rate(ruby_http_request_duration_seconds_sum{kubernetes_namespace=\"$namespace\",controller!=\"status\",controller!=\"healthz\",controller=~\"$controller\",action=~\"$action\"}[5m]) / rate(ruby_http_request_duration_seconds_count{kubernetes_namespace=\"$namespace\",controller!=\"status\",controller=~\"$controller\",action=~\"$action\"}[5m])) by (controller, action) * 1000 > 0 ",
     "legendFormat": "{{controller}}/{{action}}"
    }
   ]
  },
  {
   "title": "Request Count / s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(ruby_http_request_duration_seconds_count{kubernetes_namespace=\"$namespace\", controller!=\"status\",controller!=\"healthz\",controller=~\"$controller\",action=~\"$action\"}[5m])) by (controller, action) > 0",
     "legendFormat": "{{controller}}/{{action}}"
    }
   ]
  },
  {
   "title": "Max Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(rate(ruby_http_request_duration_seconds_sum{kubernetes_namespace=\"$namespace\",controller!=\"status\",controller!=\"healthz\",controller=~\"$controller\",action=~\"$action\"}[5m]) / rate(ruby_http_request_duration_seconds_count{kubernetes_namespace=\"$namespace\",controller!=\"status\",controller=~\"$controller\",action=~\"$action\"}[5m]) > 0)",
     "legendFormat": "Max Request",
     "target": "carbon.*"
    },
    {
     "expr": "max(rate(ruby_http_request_sql_duration_seconds_sum{kubernetes_namespace=\"$namespace\",controller!=\"status\",controller!=\"healthz\",controller=~\"$controller\",action=~\"$action\"}[5m]) / rate(ruby_http_request_sql_duration_seconds_count{kubernetes_namespace=\"$namespace\",controller!=\"status\",controller=~\"$controller\",action=~\"$action\"}[5m]) > 0)",
     "legendFormat": "Max SQL"
    }
   ]
  },
  {
   "title": "Successful Requests / s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(ruby_http_requests_total{kubernetes_namespace=\"$namespace\",status=~\"^[23].*\",controller!=\"status\",controller!=\"healthz\",controller=~\"$controller\",action=~\"$action\"}[5m])) by (status) > 0",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Avg Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(ruby_http_request_duration_seconds_sum{kubernetes_namespace=\"$namespace\",controller!=\"status\",controller!=\"healthz\",controller=~\"$controller\",action=~\"$action\"}[5m]) / rate(ruby_http_request_duration_seconds_count{kubernetes_namespace=\"$namespace\",controller!=\"status\",controller=~\"$controller\",action=~\"$action\"}[5m]) > 0)",
     "legendFormat": "Avg Request"
    },
    {
     "expr": "avg(rate(ruby_http_request_sql_duration_seconds_sum{kubernetes_namespace=\"$namespace\",controller!=\"status\",controller!=\"healthz\",controller=~\"$controller\",action=~\"$action\"}[5m]) / rate(ruby_http_request_sql_duration_seconds_count{kubernetes_namespace=\"$namespace\",controller!=\"status\",controller=~\"$controller\",action=~\"$action\"}[5m]) > 0)",
     "legendFormat": "Avg SQL"
    }
   ]
  },
  {
   "title": "Errors / s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(ruby_http_requests_total{kubernetes_namespace=\"$namespace\",status=~\"^[45].*\",controller=~\"$controller\",action=~\"$action\"}[5m])) by (status) > 0",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Slow Actions",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10,avg(rate(ruby_http_request_duration_seconds_sum{kubernetes_namespace=~\"$namespace\"}[1w]) / rate(ruby_http_request_duration_seconds_count{kubernetes_namespace=~\"$namespace\"}[1w])) by (controller, action)) \n"
    }
   ]
  },
  {
   "title": "Most Frequent Actions / Day",
   "type": "table",
   "description": "Average number of requests per day during last week",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10,sum(rate(ruby_http_request_duration_seconds_count{kubernetes_namespace=~\"$namespace\",controller!=\"status\",controller!=\"healthz\"}[1w]) * 3600 * 24) by (controller, action))"
    }
   ]
  },
  {
   "title": "Puma",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(ruby_puma_thread_pool_capacity{kubernetes_namespace=\"$namespace\"})",
     "legendFormat": "Free Threads"
    },
    {
     "expr": "sum(ruby_puma_request_backlog{kubernetes_namespace=\"$namespace\"})",
     "legendFormat": "Request Backlog"
    }
   ]
  },
  {
   "title": "Sidekiq Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Job Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ruby_sidekiq_job_duration_seconds_sum{kubernetes_namespace=\"$namespace\",job_name=~\"$job\"}[5m]) / rate(ruby_sidekiq_jobs_total{kubernetes_namespace=\"$namespace\",job_name=~\"$job\"}[5m]) > 0",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Job Count / s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ruby_sidekiq_jobs_total{kubernetes_namespace=\"$namespace\",job_name=~\"$job\"}[5m]) > 0",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Max Job Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(rate(ruby_sidekiq_job_duration_seconds_sum{kubernetes_namespace=\"$namespace\",job_name=~\"$job\"}[5m]) / rate(ruby_sidekiq_job_duration_seconds_count{kubernetes_namespace=\"$namespace\",job=~\"$job\"}[5m]) > 0)",
     "legendFormat": "Max. Duration"
    }
   ]
  },
  {
   "title": "Slow Jobs",
   "type": "table",
   "description": "Average duration of last week",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10,avg(rate(ruby_sidekiq_job_duration_seconds_sum{kubernetes_namespace=\"$namespace\"}[1w]) / rate(ruby_sidekiq_jobs_total{kubernetes_namespace=\"$namespace\"}[1w])) by (job_name))"
    }
   ]
  },
  {
   "title": "Most Frequent Jobs / Day",
   "type": "table",
   "description": "Number of runs per day during last week",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10,sum(rate(ruby_sidekiq_jobs_total{kubernetes_namespace=~\"$namespace\"}[1w]) * 3600 * 24) by (job_name))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(ruby_rss{kubernetes_namespace=~\"$namespace\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Object Allocation Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(ruby_allocated_objects_total{kubernetes_namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Heap Web",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(ruby_heap_free_slots{kubernetes_namespace=\"$namespace\",type=~\"master|web|puma_master|puma_worker\"}) by (type)",
     "legendFormat": "Min Free Slots {{type}}"
    },
    {
     "expr": "max(ruby_heap_live_slots{kubernetes_namespace=\"$namespace\",type=~\"master|web|puma_master|puma_worker\"}) by (type)",
     "legendFormat": "Max Live Slots {{type}}"
    }
   ]
  },
  {
   "title": "Heap Sidekiq Worker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(ruby_heap_free_slots{kubernetes_namespace=\"$namespace\",type=\"sidekiq\"}) without (pid)",
     "legendFormat": "Min Free Slots {{type}}"
    },
    {
     "expr": "max(ruby_heap_live_slots{kubernetes_namespace=\"$namespace\",type=\"sidekiq\"}) without (pid)",
     "legendFormat": "Max Live Slots {{type}}"
    }
   ]
  }
 ]
}